### PR TITLE
Kg13carr fix mongodb repo

### PR DESCRIPTION
**Pull request by kgcarr**
changed the repo names for the icp-mongodb to match a common installation

### CODE REVIEW

**Comment by jabbott7335** [comment]
small changes ... looks good

**Comment by kgcarr** [comment]
@patrocinio can this be merged?

**Review by patrocinio — APPROVED** [review]

**Comment by patrocinio** [comment]
+1

**Comment by kgcarr** [comment]
This PR was closed, but not merged

**Pull request merged**
